---
- name: date and time demo
  hosts: all
  gather_facts: false
  tasks:
    - name: date and time
      ansible.builtin.debug:
        msg: "{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S') }}"

    - name: iso8601 manual
      ansible.builtin.debug:
        msg: "{{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%S:%z') }}"

    - name: iso8601
      ansible.builtin.debug:
        #msg: "{{ lookup('pipe', 'date --iso-8601=seconds') }}" 
        msg: "{{ lookup('pipe', 'date --iso8601=seconds') }}" #not worked properly how should handle the error so?
      ignore_errors: true # instead of fail at process it would be ignored and error got handled